import { Block, Color, TermGame } from "./index.js";
const black = new Color(63, 68, 81);
const white = new Color(215, 218, 224);
const pieces = {
    none: " ",
    white: {
        king: "♔",
        queen: "♕",
        rook: "♖",
        bishop: "♗",
        knight: "♘",
        pawn: "♙"
    },
    black: {
        king: "♚",
        queen: "♛",
        rook: "♜",
        bishop: "♝",
        knight: "♞",
        pawn: "♟︎"
    }
};
const game = new TermGame({
    height: 8,
    width: 8,
    data: [
        new Block(pieces.black.rook, black, white),
        new Block(pieces.black.knight, white, black),
        new Block(pieces.black.bishop, black, white),
        new Block(pieces.black.queen, white, black),
        new Block(pieces.black.king, black, white),
        new Block(pieces.black.bishop, white, black),
        new Block(pieces.black.knight, black, white),
        new Block(pieces.black.rook, white, black),
        new Block(pieces.black.pawn, white, black),
        new Block(pieces.black.pawn, black, white),
        new Block(pieces.black.pawn, white, black),
        new Block(pieces.black.pawn, black, white),
        new Block(pieces.black.pawn, white, black),
        new Block(pieces.black.pawn, black, white),
        new Block(pieces.black.pawn, white, black),
        new Block(pieces.black.pawn, black, white),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.none, white, black),
        new Block(pieces.none, black, white),
        new Block(pieces.white.pawn, black, white),
        new Block(pieces.white.pawn, white, black),
        new Block(pieces.white.pawn, black, white),
        new Block(pieces.white.pawn, white, black),
        new Block(pieces.white.pawn, black, white),
        new Block(pieces.white.pawn, white, black),
        new Block(pieces.white.pawn, black, white),
        new Block(pieces.white.pawn, white, black),
        new Block(pieces.white.rook, white, black),
        new Block(pieces.white.knight, black, white),
        new Block(pieces.white.bishop, white, black),
        new Block(pieces.white.queen, black, white),
        new Block(pieces.white.king, white, black),
        new Block(pieces.white.bishop, black, white),
        new Block(pieces.white.knight, white, black),
        new Block(pieces.white.rook, black, white), // h1
    ]
});
game.render();
process.stdout.write("\n".repeat(10));
